### PR TITLE
Center the shopping bag icon along its svg

### PR DESCRIPTION
**Pull request by vickyvishal**
The shopping bag icon was not centered along the svg box as provided in figma. This PR fixes it

### Description

Describe your changes (or add ticket description) and add relevant screenshots
| Before | After |
| --- | --- |
| Screenshot 2022-11-09 at 10 01 34|Screenshot 2022-11-09 at 10 01 56
### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change

### How do I test this

- Add steps to test
- in bullet point format
- preferably you can add link to the storybook build in the PR

### Did you remember to take care of the following?

- [ ] `npm i` – for new NPM dependencies.
- [x] `npm run lint` - to check for linting issues
- [x] `npm run test` - to run unit tests
- [x] `npm run test:sh:docker` - to run screenshot tests, [detail instruction](https://hey-car.github.io/heycar-uikit/main/?path=/docs/guidelines-screenshot-testing--page)

### New Feature / Bug Fix

- [x] Run unit tests to ensure all existing tests are still passing.
- [ ] Add new passing unit tests to cover the code introduced by your pr.

Thanks for contributing!

### CODE REVIEW

**Comment by heyabinanto** [comment]
@vickyvishal screenshot test failed, just re running it that to check if its a one off case.

**Review by heyabinanto — CHANGES_REQUESTED** [review]
need to test screenshot snapshots

**Comment by esraltintas** [comment]
Hey @vickyvishal, could you update the description when you check our checklist and also please choose a type of change and new feature/bug

**Comment by heyabinanto** [comment]
@vickyvishal might need to run `test:sh:update` to update the screenshot snapshots with the updated SVGs

**Review by esraltintas — APPROVED** [review]

**Review by heyabinanto — APPROVED** [review]

**Pull request merged**
