### PR TITLE
Fix `Badge` height

### PR DESCRIPTION
**Pull request by vickyvishal**
### Description

This PR fixes the Badge style mismatch with the provided [Figma](https://www.figma.com/file/rrvkvQEoVTOHa7MzyKSaoz/OTP-Global-Design-System?node-id=4031%3A102387)
### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change

### How do I test this

- The new height of the badge should be 28px

### Did you remember to take care of the following?

- [ ] `npm i` – for new NPM dependencies.
- [ ] `npm run lint` - to check for linting issues
- [ ] `npm run test` - to run unit tests
- [ ] `npm run test:sh:docker` - to run screenshot tests, [detail instruction](https://hey-car.github.io/heycar-uikit/main/?path=/docs/guidelines-screenshot-testing--page)

### New Feature / Bug Fix

- [ ] Run unit tests to ensure all existing tests are still passing.
- [ ] Add new passing unit tests to cover the code introduced by your pr.

Thanks for contributing!

### CODE REVIEW

**Comment by esraltintas** [comment]
Hey @vickyvishal Could you check your commit, please? https://github.com/commitizen/cz-cli

**Comment by nsacerdote-heycar** [comment]
I know that nobody asked me to review this, but I think that setting a fixed height is not the way to go, what happens is someone needs a two line badge?

image

Suggestion: I would instead fix the line height discrepancy with the figma provided, I think we should add something like line-height: 20px to the label 🤔

**Comment by vickyvishal** [comment]
@nsacerdote-heycar Thank you for the review, makes sense. I am setting the `line-height` to 20px

**Review by esraltintas — APPROVED** [review]

**Review by nsacerdote-heycar — APPROVED** [review]

**Pull request merged**
