### PR TITLE
feat(icons): added updated car icons

### PR DESCRIPTION
**Pull request by hcafaq**
## Pull Request
https://heycar.atlassian.net/jira/software/projects/HEYUI/boards/312?selectedIssue=HEYUI-141

### Description

Updated car icons from design: https://www.figma.com/file/rrvkvQEoVTOHa7MzyKSaoz/OTP-Global-Design-System?node-id=1364%3A40607

image

image

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation change

### How do I test this

- Add steps to test
- in bullet point format
- preferably you can add link to the storybook build in the PR

### Did you remember to take care of the following?

- [ ] `npm i` – for new NPM dependencies.
- [x] `npm run lint` - to check for linting issues
- [x] `npm run test` - to run unit tests
- [ ] `npm run test:screenshots` - to run snapshot tests

### New Feature / Bug Fix

- [ ] Run unit tests to ensure all existing tests are still passing.
- [ ] Add new passing unit tests to cover the code introduced by your pr.

Thanks for contributing!

### CODE REVIEW

**Comment by hcafaq** [comment]
@derek-heycar I can't see updated icons right now but Icons start showing up if view-box is updated in svg viewBox="0 0 84 50"

**Review by derek-heycar — CHANGES_REQUESTED** [review]
Do you check the console log when you developing?

```
react-dom.development.js:67 Warning: Invalid DOM property `clip-rule`. Did you mean `clipRule`?
react-dom.development.js:67 Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
```

**Comment by hcafaq** [comment]
> Do you check the console log when you developing?
> 
> ```
> react-dom.development.js:67 Warning: Invalid DOM property `clip-rule`. Did you mean `clipRule`?
> react-dom.development.js:67 Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
> ```

resolved

**Pull request merged**
